### PR TITLE
Fix eslint errors

### PR DESCRIPTION
**Pull request by YuraDubensky**

### CODE REVIEW

**Comment by Morgul** [comment]
@YuraDubensky Does this fix the dropdowns on the demo page as well, or is something else wrong with that?

**Comment by Morgul** [comment]
Other than that, this looks good. :+1:

**Comment by YuraDubensky** [comment]
Unfortunatelly I cannot run demo on my local env - so I am not sure.
When I run npm run demo it succesfully builds and starts webserver but seems that it doesn't generate index.html in dist folder at all. So when i navigate to local website it displays nothing.

I am probably doing something wrong there. Any thoughts?

**Comment by Morgul** [comment]
@YuraDubensky The npm task is a little wrong. You need to run `grunt` and then run `npm run demo`. I just did a fresh checkout and that order worked for me.

**Comment by Morgul** [comment]
@YuraDubensky Just pinging you, in case the edit doesn't. Pull master and you should be able to run the demo.

**Comment by YuraDubensky** [comment]
Hey, I was able to run demo after your last changes and I can confirm that dropdowns are not working due to my changes. Its an issue with html selectors not working properly.

**Comment by YuraDubensky** [comment]
@Morgul Also fixed tooltip compatibility issue with latest boostrap (4.0.0 stable).
Looks like in release version they manage most of tooltip arrow placing using css (comparing to 4.0.0-beta.2 version on your demo).
So some 4.0.0-beta.2 ajastments to tootltip arrow inline styles are not relevant and caused issues in displaying arrow.

**Pull request merged**
