### PR TITLE
Fixe package.json for build release (npm audit fix)

### PR DESCRIPTION
**Pull request by haricot**
```
$ git clone https://github.com/Morgul/ui-bootstrap4
$ cd ui-bootstrap4
$ npm install
found 40 vulnerabilities (31 low, 2 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details

$ npm audit fix`
+ grunt-contrib-watch@1.1.0
+ marked@0.4.0
+ lodash@4.17.10
+ grunt-html2js@0.5.1
added 78 packages from 89 contrib
```

### CODE REVIEW

**Comment by haricot** [comment]
This does not solve all the problems and it is not necessarily necessary so I close this PR.

**Comment by haricot** [comment]
@morgul, Could we have a 3.0.4? please ! I use several projects that depend on it, it would be more practical. Waiting for angular 7 or other :)

**Comment by Morgul** [comment]
I'll try to get that done tonight or tomorrow.

**Comment by Morgul** [comment]
@haricot Just released v3.0.4. :)

**Pull request closed without merging**
