### PR TITLE
Master fix#7

### PR DESCRIPTION
**Pull request by YuraDubensky**
Fix for issue #7 and fix compatibility with latest boostrap.

### CODE REVIEW

**Comment by Morgul** [comment]
Looks great, thanks!

**Comment by YuraDubensky** [comment]
May I ask you when next release is planned?

**Comment by Morgul** [comment]
@YuraDubensky My vague plan is "soon". I want get your other merge request in, and fix #12 before releasing a new one.

Regarding this change; I had not pulled it to run it locally until after it was merged, but there seems to be a few issues: the linter died on a tabs vs spaces issue (easy fix), but then most of the dropdowns on the demo page stopped working. (The ones appending to body continue to work.) Is there a chance you could look at that? It seems to have been introduced by your change; I'm hesitant to make a release until that's resolved.

**Comment by YuraDubensky** [comment]
@Morgul Give me some time to setup demo page and try it out. But don't think my fix broke it, since it is working fine in my project with those changes. But I will verify and revert

**Comment by YuraDubensky** [comment]
@Morgul Are using 2 spaces indentation in sources?

**Comment by Morgul** [comment]
...yes. (I'm not happy about it either, this is a fork of the original, and I haven't had time to redo their build system, so we're stuck with the original formatting decisions.)

My recommendation is to run `grunt` before doing a merge request. That will run all unit tests, and linting.

**Comment by Morgul** [comment]
Also, @YuraDubensky, I don't want a revert; your change is a very good one. It's entirely possible the dropdowns are wrong on the demo page. I just want the make sure the demo page is working, and there wasn't any unintended side effects. :)

**Comment by YuraDubensky** [comment]
@Morgul I have fixed eslint errors for my 2 fixes and created a new pull request
https://github.com/Morgul/ui-bootstrap4/pull/16

**Pull request merged**
